language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls pytest pytest-cov
# command to run tests
script:
  - python manage.py test 
  -pytest --cov=tests
after_sucess:
  - coveralls